title: Kai Holl
# logo: ![profile picture](/images/fotor-20241230163441.png
logo: ![fotor-20241230163441](https://github.com/user-attachments/assets/8f923bf1-6a2c-496c-a893-82cf2a2e6ddf)
description: Data Analyst, MS Student
theme: jekyll-theme-minimal
