title: Kai Holl
logo: ![profile-photo](https://github.com/user-attachments/assets/6cf39777-7e10-45e6-8255-b5cb4814ed1c) 
description: Data Analyst, MS Student
show_downloads: False
theme: jekyll-theme-minimal
