title: Kai Holl
logo: ![profile_pic](https://github.com/user-attachments/assets/b4cc2c1a-b2b0-4310-9b98-044b73f1debc)
description: Data Analyst, MS Student
show_downloads: False
theme: jekyll-theme-minimal
